### PR TITLE
reducer boilerplate, actions for session, first contact with server

### PR DESCRIPTION
**Pull request by greatgabsp**
- Initial file structure using atomic design, typescript, and redux
- Service pattern for token retrieval and reading/writing http headers
- First reducers for session and groups
- First actions and connection to server through Axios

### CODE REVIEW

**Comment by brortao** [comment]
nice! this looks great :) my only comment is that we can use the auto-generated API client to get the full benefits of openAPI/swagger! https://www.npmjs.com/package/@wobbly/api-client

**Comment by brortao** [comment]
@greatgabsp actually maybe hold off on that -- i'm going to try out writing a basic XMPP connector in the frontend

**Comment by greatgabsp** [comment]
> nice! this looks great :) my only comment is that we can use the auto-generated API client to get the full benefits of openAPI/swagger! https://www.npmjs.com/package/@wobbly/api-client
> 
> this'll save having to manually write up the API contract and so on

It finally clicked in my head now what this is for!

**Comment by greatgabsp** [comment]
> @greatgabsp actually maybe hold off on that -- i'm going to try out writing a basic XMPP connector in the frontend

**Pull request merged**
